DROP TABLE IF EXISTS names;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS names (
	name TEXT NOT NULL PRIMARY KEY,
	owner TEXT NOT NULL,
	texts TEXT,
	addresses TEXT,
	contenthash TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profiles {
	name TEXT NOT NULL PRIMARY KEY,
	followers TEXT,
	following TEXT,
}

CREATE TABLE IF NOT EXISTS posts {
	name TEXT NOT NULL,
	post_id INT NOT NULL,
	likes TEXT,
	files TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	PRIMARY KEY(name, post_id),
}

CREATE TABLE IF NOT EXISTS comments {
	owner TEXT NOT NULL,
	name TEXT NOT NULL,
	post_id INT NOT NULL,
	comment TEXT NOT NULL,
	comment_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	PRIMARY KEY(name, post_id, comment_id)
}