name = "ens-gateway"
main = "src/index.ts"
compatibility_date = "2023-03-15"

[[d1_databases]]
binding = "DB"
database_name = "socioo"
database_id = "8ba6bf8a-f18c-4c66-b638-29169133e81e"

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
